name: Release docker-manager-library to npm
on:
  push:
    tags:
      - "release-v*"

permissions:
  contents: write
  packages: write
  actions: read

jobs:
  release:
    name: Release
    runs-on:
      labels: [self-hosted, ci]
    container:
      image: node:20-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library
        run: pnpm build

      - name: Print debug values
        run: |
          echo $PWD
          ls -la

      - name: Add working directory to git as safe directory
        run: |
          git config --global --add safe.directory "${PWD}"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm dlx semantic-release
