name: Release
on:
  push:
    tags:
      - 'release-v*'

jobs:
  release:
    name: Release
    runs-on:
        labels: [self-hosted, ci]
    container:
        image: node:lts
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TpOKEN }}
        run: pnpm dlx semantic-release