name: Release docker-manager-library to npm
on:
  push:
    tags:
      - "release-v*"

permissions:
  packages: write

jobs:
  release:
    name: Release
    runs-on:
      labels: [self-hosted, ci]
    container:
      image: node:20-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library
        run: pnpm build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm dlx semantic-release
