name: Run docker-manager-library tests
run-name: >-
  ${{ github.event.action == 'opened' 
    && format('{0} opened PR #{1}', github.event.pull_request.user.login, github.event.pull_request.number)
    || format('{0} updated PR #{1}', github.event.pull_request.user.login, github.event.pull_request.number) }}

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    if: github.event.pull_request.head.repo.fork == false
    runs-on:
      labels: [self-hosted, test]
    container:
        image: cruizba/ubuntu-dind:noble-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
