name: Run docker-manager-library tests
run-name: >-
  ${{ github.event.action == 'opened' 
    && format('{0} opened PR #{1}', github.event.pull_request.user.login, github.event.pull_request.number)
    || format('{0} updated PR #{1}', github.event.pull_request.user.login, github.event.pull_request.number) }}

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
